config/routes.rb
Rails.application.routes.draw do
  # root path welcome index
  root 'sessions#new'

  # blogs all paths
  resources :blogs do

    # path for the comments
    resources :comments, only: [:create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    
    # path for the likes button
    resources :like, only: [ :create, :destroy]
    
  end

  # Extra paths
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get   'registrations/edit',   to: 'registrations#edit'
  patch 'registrations/update', to: 'registrations#update'
  get 'registrations/confirm_email', to: 'registrations#confirm_email', as: 'confirm_email'
  post 'registrations/send_email_again', to: 'registrations#send_email_again', as: 'send_email_again'

  get    'sign_in',  to: 'sessions#new'
  post   'sign_in',  to: 'sessions#create', as: 'log_in'
  delete 'logout',   to: 'sessions#destroy'
  get    'password', to: 'passwords#edit',  as: 'edit_password'
  patch  'password', to: 'passwords#update'
end

app/models/blog.rb
class Blog < ApplicationRecord
  include Hashid::Rails

  has_one_attached :image, dependent: :destroy

  belongs_to :user

  has_many :comments, as: :commentable, dependent: :destroy

  has_many :likes, as: :likeable, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  scope :filter_by_name, lambda { |search|
    return if search.nil?
    where('name like ?', "%#{search}%")
  }

end 

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # get all blogs
  def index
    search_with = { user_id: @current_user.id } if params[:page_selection].present?
    @blogs = Blog.filter_by_name(params[:search]).where(search_with).paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @comments = @blog.comments
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = @current_user.blogs.new(blog_params)
    @blog.image.attach(params[:image]) if params[:image].present?
    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_path(@blog), notice: "Blog was successfully created." }
      else
        format.html { render blog_path, notice: "Something went worng."}
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_path(@blog), notice: "Blog was successfully updated." }
      else
        format.html { render blog_path, notice: "Something went worng." }
      end
    end
  end
  
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_path, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:name, :body, :image)
  end

end

app/views/blogs/_blog.html.erb
<div class="container-fluid " >
  <div class="row">    
    <div class="col">
      <div class="row">
        <div >
          <h4>
            <strong>Blog Heading :</strong>
            <%= blog.name %>
          </h4>
        </div>
      </div>
      <div class="row">
        <div >
          <h5>
            <strong>By :</strong>
            <%= blog.user.first_name %>
          </h5>
        </div>
      </div>
    </div>
    <div class="col-1">
      <% if blog.image.attached? %>
        <%= image_tag blog.image.variant(resize_to_limit: [70, 70]) %>
      <% end %>
    </div>
      <div>  
        <p> 
          <strong></strong>
          <%= simple_format blog.body %>
        </p>
      </div>
      
      <div class="row">
        <div class="col-1" id = "like_count">
          <strong>Likes:</strong>
          <%= blog.likes.count %>
        </div>
        <div class="display-inline" id = "comment_count">
          <strong>Comments : </strong>
          <%= blog.comments.count %>
        </div>           
        <div class="display-inline">
          <strong> Created At : </strong>
          <%= blog.created_at.strftime(" %d %b %Y") %>
        </div>  

        <div id="likes" >
          <%= render 'like_partials', blog: blog %>
        </div>
      </div> 
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="p-2">
    <%= form.label "Name of Blog", style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="p-2">
    <%= form.label "Put Your Content Here", style: "display: block" %>
    <%= form.text_area :body, placeholder: "Enter Blog content here", size: "70x20" %>
  </div>

  <div class="p-2">
    <%= form.label "Image For Blog", style: "display: block" %>
    <%= form.file_field :image, class: "btn btn-secondary" %>
  </div>
 
  <div class="p-2">
    <% if blog.id.nil? %>
      <%= form.submit :create, class: "btn btn-success" %>
    <% else %>
      <%= form.submit :update, class: "btn btn-success" %>
    <% end %>

  </div>
<% end %>

app/views/blogs/_index_blogs.html.erb
<div class="container-fluid py-4" >
  <div class="row">
    <div class="col-10">
      <div class="row">
        <div >
          <h4>
            <strong>Blog Heading :</strong>
            <%= blog.name %>
          </h4>
        </div>
      </div>
      <div class="row">
        <div >
          <h5>
            <strong>By :</strong>
            <%= blog.user.first_name %>
          </h5>
        </div>
      </div>
      <div class=" row overflow-hidden" style="height: 50px;">  
      <p>
        <strong></strong>
        <%= blog.body %>
      </p>
    </div>
    </div>
    <div class="col-2">
      <% if blog.image.attached? %>
        <%= image_tag blog.image.variant(resize_to_limit: [170, 120]) %>
      <% end %>
    </div>
  </div>
        <%= link_to "Continue Reading This Blog", blog, class: "link-primary" %>
    <div class="row">  
      <div class="display-inline" id = "like_count">
        <strong>Likes : </strong>
        <%= blog.likes.count %>
      </div>
      <div class="display-inline">
        <strong>Comments : </strong>
        <%= blog.comments.count %>
      </div>           
      <div class="display-inline">
        <strong> Created At : </strong>
        <%= blog.created_at.strftime(" %d %b %Y") %>
      </div>        
    </div>
</div>

app/views/blogs/_like_partials.html.erb
<div id="<%="#{dom_id(blog)}_like"%>">
  <% like = blog.likes.find_by(user_id: @current_user.id) %>
  <% if like.present? %>
    <%= form_with url: blog_like_path(blog.id, like.id), method: :delete, format: :turbo_stream do |form| %>
      <%= form.submit "Unlike", class: 'btn btn-primary'  %>
    <% end %>
  <% else %>
    <%= form_with url: blog_like_index_path(blog.id), method: :post, format: :turbo_stream do |form| %>
      <%= form.submit "like", class: 'btn btn-outline-primary'  %>
    <% end %>
  <% end %>
</div>

app/views/blogs/_new_comment.html.erb
<!-- form to create a comment in blogs -->
<div class = "row" >
  <% if form_of == 'comment' %>
    <% url = "/blogs/#{@blog.id}/comments/#{commentable.id}/comments" %>
  <% else %>
    <% url = "/blogs/#{@blog.id}/comments" %>
  <% end %>
  <%= form_with url: "#{url}", method: :post, class: "" do |form| %>
    <div class="row">
      <div class="col">
        <%= form.text_field :comment_body, class: "w-100", placeholder: "reply here" %>
      </div>
      <div class="col-2">
        <%= form.submit 'comment', class: 'btn btn-primary btn-sm' %>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/_show_comment.html.erb
<div class="container  comment-section" style="overflow-y: auto; padding-left: 40px;">


<% commentable.comments.order('created_at desc').each do |comment| %>
<div id="<%= "#{dom_id(comment)}_item" %>">
  <div class="container-fluid mt-5">
      <div class="">
          <div class="col-md-8">
              <div class="d-flex flex-column comment-section">
                  <div class="bg-white p-2">
                      <div class="d-flex flex-row user-info ">
                        <%= image_tag comment.user.avatar.variant(resize_to_limit: [50, 50]) if comment.user.avatar.attached?%>
                          <div class="d-flex flex-column justify-content-start ml-2"><span class="d-block font-weight-bold name">
                            <%= comment.user.first_name %>                          
                          </span><span class="date text-black-50">Shared publicly - <%= comment.created_at.strftime(" %d %b %Y") %></span></div>
                      </div>
                      <div class="mt-1 pl-3 ">
                          <p class="comment-text">
                            Say:  <%= comment.comment_body %>
                          </p>
                          <%= comment.comments.count %> : Reply 
                      </div>
                  </div>
                  
                  <div class="bg-light p-2">
                      <div class="d-flex flex-row align-items-start">
                        <%= image_tag @current_user.avatar.variant(resize_to_limit: [30 , 30]) if @current_user.avatar.present? %>
                        <%= render :partial=>"blogs/new_comment", locals: { commentable: comment, form_of: 'comment'} %>
                      </div>

                    <% if  comment.user.id == @current_user.id %>
                      <% if commentable.class.name == 'Blog' %>
                        <%= button_to 'Delete Comment',[commentable , comment ], remote: true, turbo: false, method: :delete, class: "btn btn-primary btn-sm" %>
                      <% else %>
                        <%= button_to 'Delete Comment',[@blog, commentable , comment ], remote: true, turbo: false, method: :delete, class: "btn btn-primary btn-sm" %>
                      <% end %>
                    <% end %>
                  </div>
              </div>
          </div>
      </div>
  </div>
  
  <% if comment.comments.present? %>
    <div class="" style="padding-left: 20px; padding-top: 7px;">
      <%= render :partial=>"blogs/show_comment", locals: {commentable: comment} %>
    </div>
  <% end %>


</div>
<% end %>

</div>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

  <!-- Cheak User And Blog User Is Same -->

  <% if @blog.user.id == @current_user.id %>
    <%= render "form", blog: @blog %>
  <% else %>
    <strong>You Don't have Permission To Change This Blog</strong>
  <% end %>
<br>


<div>
  <%= link_to "Show this blog", @blog, class: "btn btn-primary" %> |
  <%= link_to "Back to blogs", blogs_path, class: "btn btn-primary" %>
</div>

app/views/blogs/index.html.erb
<!-- blog index heading part-->
<p>
  <div class="row">
    <div class="col-8">
      <h1>Here Are Some Interesting Blogs For You !!</h1>
    </div>
    <div class="col">
      <%= form_with url: blogs_path, method: :get, class: "form-inline my-2 my-lg-0" do |form| %>
        <%= form.text_field :search, class: "form-control mr-sm-2", placeholder: "Search", aria_label:"Search", value: params[:search] %>
        <%= form.hidden_field :page_selection, value: params[:page_selection] %>
      <% end %>
    </div>
  </div>
</p>
<!-- pagination logic -->
  <div class="row margin-twenty5-zero pagination-row">
    <div class="padding-zero"> 
      <ul class="pagination">
        <li class="disabled">
          <!-- logic that add pages (pagination) to application -->
          <div class = "container-fluid" id="blogs">
            <%= will_paginate(@blogs,:previous_label => "Previous", :next_label => "Next;",:class=>"small-font",:outer_window => 1,:inner_window => 1) %>
            <!-- print blogs one by one -->
            <% @blogs.each do |blog| %>
              <%= render partial: "index_blogs", locals: { blog: blog }  %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
<div class="col-lg-4 col-md-4 col-sm-5 col-xs-6 pagination-info">
  <span class="pull-right"><%= page_entries_info(@blogs) %></span>
</div>

<div class="">
  <%= will_paginate(@blogs,:previous_label => "Previous", :next_label => "Next;",:class=>"small-font",:outer_window => 1,:inner_window => 1) %>
</div>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<div>
  <%= link_to "Back to blogs", blogs_path, class: "btn btn-primary" %>
</div>

app/views/blogs/show.html.erb
<!-- show this blog -->
<%= render 'blog', blog: @blog %>
<!-- Logic to check the user and blog_user is the same -->
<div class="d-flex p-1">
  <% if (@current_user.id == @blog.user_id) %>
    <div class="p-1">
      <%= link_to "Edit this blog", edit_blog_path(@blog), class: "btn btn-primary" %> 
    </div>
    <div class="p-1">
      <%= button_to "Destroy this blog", @blog, method: :delete, class: "btn btn-danger", onclick: "return confirmDestroy('Are you sure ?')" %>
    </div>
  <% end %>
  <div class="p-1">
    <%= link_to "Back to blogs", blogs_path, class: "btn btn-primary" %>
  </div>
</div>

<!-- logic for comments -->
<!-- render add comment by the new comment partials -->
<div id="new_comment_for_blog">
  <%= render :partial=>"blogs/new_comment", locals: {commentable: @blog, form_of: 'blog'} %>
</div>
<div id="comments_of_blog" style="overflow-y: auto; max-height: 150vh;">
  <!-- Print all Comments on Blogs -->
  <%= render partial: 'blogs/show_comment', locals: { commentable: @blog }%>
</div>

<script>
  function confirmDestroy(message) {
    if (!confirm(message)) {
      return false;
    }
  }
</script>