config/routes.rb
Rails.application.routes.draw do
  # root path welcome index
  root 'sessions#new'

  # blogs all paths
  resources :blogs do

    # path for the comments
    resources :comments, only: [:create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    
    # path for the likes button
    resources :like, only: [ :create, :destroy]
    
  end

  # Extra paths
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get   'registrations/edit',   to: 'registrations#edit'
  patch 'registrations/update', to: 'registrations#update'
  get 'registrations/confirm_email', to: 'registrations#confirm_email', as: 'confirm_email'
  post 'registrations/send_email_again', to: 'registrations#send_email_again', as: 'send_email_again'

  get    'sign_in',  to: 'sessions#new'
  post   'sign_in',  to: 'sessions#create', as: 'log_in'
  delete 'logout',   to: 'sessions#destroy'
  get    'password', to: 'passwords#edit',  as: 'edit_password'
  patch  'password', to: 'passwords#update'
end

app/views/layouts/_footer.html.erb
<br>
<footer class="page-footer font-small special-color-dark  bg-dark pt-4 mt-auto">
  
  <div class="footer-copyright text-center py-3" style="color:white">
    © 2022 Copyright:
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top " id="header">
  <div class="container-fluid ">
    <%= link_to 'BlogApp', blogs_path,class: "navbar-brand" %>  
    <div class="navbar navbar-expand d-flex .px-4 " id="navbarNav">
      <ul class="navbar-nav  ms-auto">
        <li class="nav-item active ">          
          <%= link_to 'Home', blogs_path, class: "nav-link" %>        
        </li>
        <li class="nav-item">
          <%= link_to 'show my blogs', blogs_path(page_selection: "current_user_blogs"), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "create New blog", new_blog_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit My Profile', registrations_edit_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="nav justify-content-end">
        <li class="nav-link" style="color:white;">
          Logged in as: <%= @current_user.first_name %>
          <%= image_tag @current_user.avatar.variant(resize_to_limit: [30 , 30]) if @current_user.avatar.present? %>
        </li>
        <li class="nav-item navbar-nav">
          <%= button_to 'Logout', logout_path, method: :delete, class: "btn btn-danger", onclick: "return confirmDestroy('Are you sure want to Logout?')"  %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<script>
  function confirmDestroy(message) {
    if (!confirm(message)) {
      return false;
    }
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogprojecttwo</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/header' %>
    <% if alert.present? %>
      <p class="alert alert alert-primary"><%= alert %></p>
    <% end %>
    <% if notice.present? %>
      <p class="notice alert alert-primary"><%= notice %></p>
    <% end %>
    <br>
    <div class="container shadow-lg bg-white rounded center" id="main-container">
      <div class="container .mt-4">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogprojecttwo</title>
    <!-- Bootstrap Css Path -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% if alert.present? %>
      <p class="alert alert alert-primary"><%= alert %></p>
    <% end %>
    <% if notice.present? %>
      <p class="notice alert alert-primary"><%= notice %></p>
    <% end %>
    <div class="from" style="padding-top: 10vh;">
      <div class="container shadow-lg bg-white rounded center d-flex">
        <div class="container .mt-4 d-flex ">
          <div class="">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>